### ISSUE TITLE
photo folder - where is it?

### ISSUE THREAD

**Issue by ExperiDev1** [ExperiDev1/T1basic130118#6]
I can't see the photo folder anywhere. Where is it? Can i just drag photos into it?

**Comment by ExperiDev1** [comment]
I think i have found the folder now but I am not sure how to get the photos into it.
The photos are in a photos folder on my Windows 10 laptop. Can't seem to drag them or select them to get them into the folder. I will try pasting to clipboard.

**Comment by AppaApps** [comment]
Click on the images folder on GH to open the folder. Now click on the "upload files" button in the upper right corner.  You should be able to upload files from here.  If not, please attach a screen shot showing me the problem?

**Comment by ExperiDev1** [comment]
Thanks. Photos are now in correct folder.
